version: "3.9"
services:

  user-service:
    build:
      context: ./user-service
      dockerfile: ./docker/Dockerfile
    container_name: user_service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/twitter_clone
      - ADDR=8002
      - REDIS_ADDR=redis:6379
    depends_on:
      - db
      - redis
      - tweet-service
    volumes:
      - ./user-service:/app

  tweet-service:
    build:
      context: ./tweet-service
      dockerfile: ./docker/Dockerfile
    container_name: tweet_service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/twitter_clone
      - ADDR=8001
      - REDIS_ADDR=redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - ./tweet-service:/app

  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]  # Enable persistence

volumes:
  postgres_data:
    driver: local
