version: "3.8"
services:
  app:
    build: .
    container_name: twitter_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
        - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
        - REDIS_ADDR=redis:6379
  db:
    image: postgres:17
    container_name: twitter_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent storage for PostgreSQL data
  redis:
    image: redis:7
    container_name: twitter_redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]  # Enable persistence
  migrate:
    build: .
    container_name: twitter_migrate
    depends_on:
      - db
    entrypoint: >
      goose -dir migrations postgres 
      postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB} up
volumes:
  postgres_data:
    driver: local
