version: "3.9"
services:

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8000:80" # Expose port 8000 for accessing the gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Use a custom NGINX config file
    depends_on:
      - user-service
      - tweet-service

  user-service:
    build:
      context: ./user-service
      dockerfile: ./docker/Dockerfile
    container_name: user_service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/twitter_clone
      - ADDR=8002
      - REDIS_ADDR=redis:6379
    depends_on:
      - postgres
      - redis
      - tweet-service
    volumes:
      - ./user-service:/app

  tweet-service:
    build:
      context: ./tweet-service
      dockerfile: ./docker/Dockerfile
    container_name: tweet_service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/twitter_clone
      - MONGO_URI=mongodb://root:example@mongo:27017
      - ADDR=8001
      - REDIS_ADDR=redis:6379
    depends_on:
      - postgres
      - redis
      - mongo
    volumes:
      - ./tweet-service:/app

  postgres:
    image: postgres:17
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]  # Enable persistence

volumes:
  postgres_data:
    driver: local
